# 서버 포트 설정
server:
  port: 8082

# jwt
jwt:
  secret: testpallet.server.javaspringinduk

# database 연동 설정
spring:
  # spring security 기본 name, password 설정
  security:
    user:
      name: user
      password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://nc-database.cblgksyvpiho.ap-northeast-2.rds.amazonaws.com:3306/ncDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username: admin
    # password: nerdconnection
    url: jdbc:mysql://localhost:3306/nc_server?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false



# spring data jpa 설정
#jpa:
#  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  open-in-view: false
#  show-sql: true
#  hibernate:
#    ddl-auto: update



# mybatis
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

# Spring Security 로깅 설정
logging:
  level:
    org.springframework.security: DEBUG